version: "3.9"
services:
  react-app:
    build: 
      context: ./react-app
      dockerfile: ./Dockerfile.dev
    container_name: iab330reactapp
    hostname: iab330reactapp
    ports: 
      - "3000:3000"
    volumes: 
      - ./react-app/src:/app/src
    environment: 
      - WATCHPACK_POLLING=true