version: "3.9"
services:
  react-app:
    build: 
      context: ./react-app
      dockerfile: ./Dockerfile.prod
    container_name: iab330reactapp
    hostname: iab330reactapp
    ports: 
      - "8080:80"
    environment: 
      - WATCHPACK_POLLING=true