version: "3.9"
services:
  nodered:
    image: chadrogers00/node-red
    container_name: iab330nodered
    hostname: iab330nodered
    ports: 
      - "1880:1880"
    volumes:
      - ./nodered:/data
  react-app:
    build: 
      context: ./react-app
      dockerfile: ./Dockerfile.dev



